name: AutoPickup
version: ${project.version}
main: io.felux.autopickup.AutoPickup
api-version: 1.13
authors: [Felux]
description: A simple, easy to use plugin for automatic item pickup.
website: https://felux.io/
